name: Deploy with CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          cd infra
          npm ci

      - name: CDK Bootstrap
        run: |
          cd infra
          cdk bootstrap

      - name: CDK Deploy
        run: |
          cd infra
          cdk deploy --all --require-approval never